creature_name=input("Please enter Creature Name: ")
discovered_planet=input("Please enter Discoverd Planet: ")
creature_diet=input("Please enter Creature's Diet: ")
scientist_name=input("Please enter Lead Scientist's Name: ")
discovery_year=input("Please enter discovery year: ")
print("\n\n=============================================")
print("          XENO-BIOLOGY FIELD REPORT")
print("=============================================")
print()
print("Scientist:   Dr. " + scientist_name)
print("Discovery Year: " + discovery_year)
print()
print("---------------------------------------------")
print("Creature Name: " + creature_name)
print("Home Planet:   " + discovered_planet)
print("Primary Diet:  " + creature_diet)
print()
print("Scientific Designation: " + discovered_planet + "-" + creature_name +"-" + discovery_year + "")
print("=============================================\n\n")