print("Let's write a story! Please provide some words.")
adjective = input(" Modest: ")
noun = input(" development: ")
verb_past_tense = input("knew: ")
print("\nHere is your story:")
print("The " + adjective + " " + noun + " " + verb_past_tense + " over the lazy dog.")
